config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root to: "pages#home"
  # hompage
  resources :users
  resources :shows
  resources :jokes
  # necessary routes
  resources :clubs do
    resources :shows
  end
  # nested route shows/clubs use clubs and cities on home page to demonstrate
  # example - http://localhost:3000/clubs/1/shows

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true

  has_many :shows
  has_many :users, through: :shows
end

app/models/joke.rb
class Joke < ApplicationRecord
  validates :topic, presence: true
  validates :body, presence: true

  belongs_to :user
end

app/models/show.rb
class Show < ApplicationRecord
  validates :date, presence: true
  validates :name, presence: true

  belongs_to :user
  belongs_to :club

  def self.filter_by_club(id)
    where(club_id: id)
  end

  def self.get_shows_index(user, params)
    if params[:club_id]
      @shows = Show.all.filter_by_club(params[:club_id])
    elsif user
      @shows = user.shows
    else
      @shows = Show.all
    end
  end
   
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :jokes
  has_many :shows
  has_many :clubs, through: :shows
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, omniauth_providers: [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:home] 

  before_action :logged_in?

  helper_method :current_user, :logged_in?


  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = "You must be loogged in to perform that action"
      redirect_to root_path
    end
  end

  private

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @clubs = Club.all
  end

  def show
    @club = Club.find_by(params[:id])
  end

end

app/controllers/jokes_controller.rb
# frozen_string_literal: true

class JokesController < ApplicationController

  before_action :set_joke, only: %i[show update destroy edit]

  def index
    @jokes = current_user.jokes
  end

  def new
    @joke = Joke.new
  end

  def create
    @joke = current_user.jokes.build(joke_params)
    if @joke.save
      flash[:notice] = "Your comedy gold has been stored in the vault."
      redirect_to joke_path(@joke)
    else
      render :new
    end
  end

  def update
    if @joke.update(joke_params)
      redirect_to joke_path(@joke)
    else
      render :edit
    end
  end

  def destroy
    @joke.destroy
    redirect_to jokes_path
  end

  private

  def set_joke
    @joke = current_user.jokes.find_by_id(params[:id])
  
  end

  def joke_params
    params.require(:joke).permit(:topic, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end
  
end

app/controllers/shows_controller.rb
# frozen_string_literal: true

class ShowsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_show, only: %i[show update destroy edit]


  def index
    if logged_in? && params[:club_id]
        @club = Club.find_by_id(params[:club_id])
        @shows = current_user.shows.filter_by_club(params[:club_id])
    else
      @shows = Show.get_shows_index(current_user, params)
    end
  end

  def new
    @show = if @club = Club.find_by_id(params[:club_id])
      @club.shows.build
    else
      Show.new
    end
  end

  def create
    @show = current_user.shows.build(show_params)
    if @show.save
      flash[:notice] = "Your Show has been stored in the vault."
      redirect_to show_path(@show)
    else
      render :new
    end
  end

  def show
    @show = current_user.shows.find(params[:id])
  end


  def update
    if @show.update(show_params)
      redirect_to show_path(@show)
    else
      render :edit
    end
  end

  def destroy
    @show.destroy
    redirect_to shows_path
  end

  private

  def set_show
    @show = Show.find_by(params[:id])
  end

  def show_params
    params.require(:show).permit(:name, :date, :club_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clubs/index.html.erb
<h1>All of our Vault affiliated clubs</h1>

<%= link_to "Home Page", root_path%> <% if user_signed_in? %> | <%= link_to "User Home", user_path(current_user.id)%> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>

<p>
  <br>
<%= "Click the name of a club to see and upcoming gigs you have there." %>
</p>

<% @clubs.each do |club| %>
  <div>
    Club Name: <%= link_to club.name, club_shows_path(club) %><br>
    Location:
    <%= club.address %><br>
    <label for="">-------------------------</label><br>
  </div>
<% end %>

<%else%>
<p>
<% @clubs.each do |club| %>
  <div>
    <%= link_to club.name, club_shows_path(club) %><br>
    Location:
    <%= club.address %><br>
    <label for="">-------------------------</label><br>
  </div>
<% end %>
</p>
<%end%>
<br>

app/views/clubs/show.html.erb
<h1>The Club</h1>
<body>

  Venue :<p><%= @club.name %></p>
  <p><%= @club.address %></p>

</body>

<% if @club.errors.any? %>
  <ul>
    <%   @club.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end%>
  </ul>
<%end%>

<a href="/">Your Vault homepage</a><br>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>

app/views/jokes/_form.html.erb
<%= form_for @joke do |f| %>
<% if @joke.errors.any? %>
  <ul>
    <% @joke.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <%end%>
  </ul>
<%end%>
<p style="color:#121212">
  <font color="white">This is some text!</font>
  <%=f.label :topic%> <br>
  <%=f.text_field :topic, size: "50X2"%> <br>
  <br>
  <%=f.label :body%> <br>
  <%=f.text_area :body, size: "100x10"%>
  </p>
  <p>
  <%= f.submit "Save joke to your Vault"%>
</p>
<% end %>

app/views/jokes/edit.html.erb
<%= link_to "Home Page", root_path%> | <%= link_to "User Home", user_path(current_user.id)%> | <%=link_to "Joke Vault", jokes_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<h1>edit page</h1>

<%= render 'form' %>

<p><%= link_to "Delete", joke_path, method: :delete%>
|
<a href="/jokes">Go home</a></p>

<br>

<a href="/">Your Vault homepage</a><br>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>

app/views/jokes/index.html.erb
<%= link_to "Home Page", root_path%> <% if user_signed_in? %> | <%= link_to "User Home", user_path(current_user.id)%> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<br>
<br><h1>All Jokes in Vault</h1>
<p>
<%= link_to "Create a new joke", new_joke_path %> <br>
</p>

<div>
  <% @jokes.each do |joke| %>
    <p style="color:white">
      <label for="">Joke Topic:</label>
      <%= joke.topic %><br>
      <label for="">
        <bdi dir="rt l"></bdi>Body of joke: :</label><%= joke.body %><br>
        <label for=""><%= joke.id %></label><br>
        <label for=""><%= joke.user.name %></label><br>
      <%= link_to 'Edit or Delete Joke', edit_joke_path(joke) %> <br>

      <label for="">-------------------------</label><br>


      </p>
</div>
  <% end %>




<%end%>

app/views/jokes/new.html.erb
<%= link_to "Home Page", root_path%> | <%= link_to "User Home", user_path(current_user.id)%> | <%=link_to "Joke Vault", jokes_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<h2>Start writing joke</h2>



<%= render 'form' %>

app/views/jokes/show.html.erb
<%= link_to "Home Page", root_path%> | <%= link_to "User Home", user_path(current_user.id)%> | <%=link_to "Joke Vault", jokes_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>

</p><h1>Would you like to make it funnier? Maybe you should.</h1>

<h4>Click edit below to make changes</h4>

<br>
<body>
<p style="color:white">
  Title of Joke:<%= @joke.topic %>

  Joke body:<%= @joke.body %>

  </p>

</body>

<a href="/jokes/<%= @joke.id %>/edit">Edit or Delete Joke<br></a><br>
<a href="/jokes">Back to Joke Vault</a></p>

<% if @joke.errors.any? %>
  <ul>
    <% @joke.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end%>
  </ul>
<%end%>

<a href="/">Your Vault homepage</a><br>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
</p>

app/views/layouts/_navigation.html.erb
  <%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <link rel="icon" href="/assets/images/comedy_vault.png" type="icon">
    <title>The Comedy Vault</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg|%>
      <ul>
        <li>
          <%= msg %>
        </li>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<html lang="en" dir="ltr">

<head>
  <link rel="stylesheet" type="text/css" href="assets/stylesheets/normalize.css">
  <link rel="stylesheet" type="text/css" href="assets/stylesheets/grid.css">
  <link rel="stylesheet" type="text/css" href="assets/stylesheets/style.css">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,300,300i,400&display=swap" rel="stylesheet">
  <meta charset="utf-8">
  <title>Omnifood</title>
</head>
<body>
  <header>
    <nav>
      <div class="row">

  <%= image_tag "comedy_vault.png", :width => 150, :height => 150 %>
        <ul class="main-nav">
          <li><a href="/users/sign_in">Login/Home | Sign up</a></li>
          <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
          <li><%= link_to "Clubs and cities", clubs_path %></li>
          <li><a href="/shows">Upcoming Shows</a></li>
        </ul>
      </div>
    </nav>
    <div class="hero-text-box">
      <h1>Say goodbye to small crowds.<br> Hello world.</h1>
      <a class="btn btn-full" href="#">I’m Funny</a>
      <a class="btn btn-ghost" href="#">Show me more </a>
    </div>

  </header>
>


</body>

</html>

app/views/shows/_form.html.erb
<%= form_for @show do |f| %>
<% if @show.errors.any? %>
  <ul>
    <% @show.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <%end%>
  </ul>
<%end%>
<p>

  <%=f.label :date%><br>
  <%=f.date_field :date, size: "50X2"%>
  <br>

  <br>
  <%=f.label :name%>
  <br>
  <%=f.text_field :name, size: "50X2"%>

  <% if params[:club_id] %>
    <%= f.hidden_field :club_id %>
  <% else %>

    <%=f.label :club%>
    <br>
    <%=f.collection_select :club_id, Club.all, :id, :name %>

  <% end %>

</p>

<p>
  <%= f.submit "Save show to your Vault"%>
</p>
<% end %>

app/views/shows/edit.html.erb
<%= link_to "Home Page", root_path%> | <%= link_to "User Home", user_path(current_user.id)%> | <%=link_to "All Shows", shows_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<h1>edit page</h1>



<%= render 'form' %>

app/views/shows/index.html.erb
<%= link_to "Home Page", root_path%> |<% if user_signed_in? %> <%= link_to "User Home", user_path(current_user.id)%> | <%=link_to "All Shows", shows_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<%= form_tag('/shows', method: 'get') do %>

<%= select_tag('club_id', options_from_collection_for_select(Club.all, :id, :name), prompt: "Filter Shows by Club" ) %>
<%= submit_tag "Sort" %>


<% end %>





<h1>All your upcoming shows in the Vault</h1>
<p> <% if @club %>
<%= link_to "Create a new Show for this club", new_club_show_path(@club) %>
  <% else %>
<%= link_to "Create a new Show", new_show_path %>
  <% end %>
  <% end %>
</p>
  <% @shows.each do |show| %>
    <div>
      <label for="">Venue Name</label>
      <%= show.club.name %><br>
      <label for="">show Name</label>
      <%= show.name %><br>
      <label for="">Comedian Name</label>
      <%= show.user.email %><br>
      <label for="">
        <bdi dir="rtl"></bdi>date of show: :</label><%= show.date %><br>

      <a href="/shows/<%= show.id %>/edit">Edit or Delete show<br></a>
      <label for="">-------------------------</label><br>
    </div>

  <% end %>

  <br>
  <br>

  <%else%>

  <% if @club == false %>
    <% @shows.each do |show| %>
      <div>
        <%= show.club.name %><br> Presents<br>
        <%= show.user.email %> Performing <br>
        <%= show.name %>

        Show Date and time:<p><%= show.date.strftime ("%m/%d/%Y")%>, <%=show.date.strftime("%I:%M:%S %p") %>
      </div>

    <% end %>

<% end %>

app/views/shows/new.html.erb
<%= link_to "Home Page", root_path%> | <%= link_to "User Home", user_path(current_user.id)%> | <%=link_to "All Shows", shows_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<h2>Start writing show</h2>


<%= render 'form' %>

app/views/shows/show.html.erb
<%= link_to "Home Page", root_path%> | <%= link_to "User Home", user_path(current_user.id)%> | <%=link_to "All Shows", shows_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<body>
  <p>
<h1>Show was booked!</h1><br>
</p>


Show Date and time:<p><%= @show.date.strftime ("%m/%d/%Y")%>, <%=@show.date.strftime("%I:%M:%S %p") %> </p>

Comedian Name:<p><%= @show.user.name %></p>
Show Name:<p><%= @show.name %></p>


Venue :<p><%= @show.club.name %> <br>
<%= @show.club.address %></p>

</body><br>

<% if @show.errors.any? %>
  <ul>
<%   @show.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
    <%end%>
    </ul>
  <%end%>

app/views/users/show.html.erb
<%= link_to "Home Page", root_path%> | <%= link_to "Logout", destroy_user_session_path, method: :delete %> <br>

<p><br>
  <br>
  <a href="/jokes">Enter your Joke vault.</a><br>
  <a href="/shows">Anounce a show, edit the details, or see all your upcoming events.</a><br>
  <%= link_to "affiliated clubs", clubs_path %> <br>
</p>

<style>
  body {
    background-image: url('https://upload.wikimedia.org/wikipedia/commons/8/87/WinonaSavingsBankVault.JPG');
    background-position: center;
    background-size: cover;
    height: 110vh;

  }
  </style>